name: Generate Podcast Feeds
on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures GITHUB_TOKEN is available for push

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'  # Corrected spacing

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Feed Generator
        run: python feed.py

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "shehbaz@khu.ac.kr"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Modified Feed" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
